require("loops.pack.icons")
require("loops.pack.treesitter")
require("loops.pack.nvim-surround")
require("loops.pack.lsp")
require("loops.pack.fzf")
require("loops.pack.oil")
require("loops.pack.harpoon")
require("loops.pack.fugitive")
