# Keymap
set -g prefix M-m
bind -n M-m send-prefix

unbind C-b
bind-key -r x kill-pane

unbind '"'
bind v split-window -h
bind | split-window -h -c "#{pane_current_path}"

unbind %
bind s split-window -v
bind - split-window -v -c "#{pane_current_path}"

bind-key -r H swap-pane -U
bind-key -r L swap-pane -D

bind-key -n -r M-Left  resize-pane -L 5
bind-key -n -r M-Right resize-pane -R 5
bind-key -n -r M-Up    resize-pane -U 5
bind-key -n -r M-Down  resize-pane -D 5

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'
bind-key -n 'M-\' if-shell "$is_vim" 'send-keys M-\\'  'select-pane -l'
bind-key -T copy-mode-vi 'M-h' select-pane -L
bind-key -T copy-mode-vi 'M-j' select-pane -D
bind-key -T copy-mode-vi 'M-k' select-pane -U
bind-key -T copy-mode-vi 'M-l' select-pane -R
bind-key -T copy-mode-vi 'M-\' select-pane -l
